TRAIN = r'e:\FInal Year Project\LDACode\train.py'
with open(TRAIN, 'r', encoding='utf-8') as f:
    c = f.read()

LOSO_BLOCK = (
    '\n'
    '# ===============================================================\n'
    '# LEAVE-ONE-SUBJECT-OUT (LOSO) EVALUATION\n'
    '# Train on all subjects except one, test on the held-out subject.\n'
    '# Repeated for every subject -- strongest cross-subject protocol.\n'
    '# Uses FINAL_K and FINAL_SH from fold-based grid search.\n'
    '# ===============================================================\n'
    'print("\\n" + "="*60)\n'
    'print("LOSO CROSS-SUBJECT EVALUATION")\n'
    'print("="*60)\n'
    '\n'
    'loso_trial_rows = []\n'
    'loso_win_rows   = []\n'
    'loso_accs       = []\n'
    '\n'
    'for loso_sid in sorted(set(allSID)):\n'
    '    te_m = (allSID == loso_sid)\n'
    '    tr_m = ~te_m\n'
    '    if te_m.sum() == 0 or tr_m.sum() == 0:\n'
    '        continue\n'
    '\n'
    '    vt_l = VarianceThreshold(threshold=0.001)\n'
    '    vt_l.fit(allF_raw[tr_m])\n'
    '    trF_l = vt_l.transform(allF_raw[tr_m])\n'
    '    teF_l = vt_l.transform(allF_raw[te_m])\n'
    '\n'
    '    mu_l = trF_l.mean(axis=0)\n'
    '    sd_l = np.where(trF_l.std(axis=0) < 1e-8, 1.0, trF_l.std(axis=0))\n'
    '    trF_l = np.clip((trF_l - mu_l) / sd_l, -10, 10)\n'
    '    teF_l = np.clip((teF_l - mu_l) / sd_l, -10, 10)\n'
    '\n'
    '    trY_l = allY[tr_m]; teY_l = allY[te_m]; teTK_l = allTK[te_m]\n'
    '\n'
    '    sub_l = (np.random.RandomState(42).choice(len(trF_l), 2000, replace=False)\n'
    '             if len(trF_l) > 2000 else np.arange(len(trF_l)))\n'
    '    mi_l  = mutual_info_classif(trF_l[sub_l], trY_l[sub_l], random_state=42, n_neighbors=5)\n'
    '    fi_l  = np.argsort(-mi_l)[:FINAL_K]\n'
    '\n'
    '    try:\n'
    '        clf_l = LinearDiscriminantAnalysis(solver="lsqr", shrinkage=FINAL_SH)\n'
    '        clf_l.fit(trF_l[:, fi_l], trY_l)\n'
    '        probs_l = clf_l.predict_proba(teF_l[:, fi_l])\n'
    '        preds_l = np.argmax(probs_l, axis=1)\n'
    '    except Exception as ex:\n'
    '        print(f"  [LOSO] {loso_sid} failed: {ex}")\n'
    '        continue\n'
    '\n'
    '    win_acc = float((preds_l == teY_l).mean())\n'
    '    loso_accs.append((loso_sid, win_acc, int(te_m.sum())))\n'
    '\n'
    '    for tkey in sorted(set(teTK_l)):\n'
    '        m  = (teTK_l == tkey)\n'
    '        pr = probs_l[m]; pd = preds_l[m]; tl = int(teY_l[m][0])\n'
    '        for r in range(len(pd)):\n'
    '            loso_win_rows.append({\n'
    '                "subject": loso_sid, "trial_key": tkey, "window_idx": r,\n'
    '                "true_idx": tl, "true_label": IDX_TO_LABEL[tl],\n'
    '                "pred_idx": int(pd[r]), "pred_label": IDX_TO_LABEL[int(pd[r])],\n'
    '            })\n'
    '        pi, conf, mp = trial_vote_from_probs(pr)\n'
    '        loso_trial_rows.append({\n'
    '            "subject": loso_sid, "trial_key": tkey, "n_windows": int(m.sum()),\n'
    '            "true_idx": tl, "true_label": IDX_TO_LABEL[tl],\n'
    '            "trial_pred_idx": pi, "trial_pred_label": IDX_TO_LABEL[pi],\n'
    '            "trial_confidence": conf,\n'
    '        })\n'
    '    print(f"  Subject {loso_sid}: win_acc={win_acc:.3f}  n_wins={int(te_m.sum())}")\n'
    '\n'
    'pd.DataFrame(loso_trial_rows).to_csv("/kaggle/working/loso_trial_predictions.csv",  index=False)\n'
    'pd.DataFrame(loso_win_rows  ).to_csv("/kaggle/working/loso_window_predictions.csv", index=False)\n'
    '\n'
    'loso_win_df   = pd.DataFrame(loso_win_rows)\n'
    'loso_trial_df = pd.DataFrame(loso_trial_rows)\n'
    '\n'
    'if len(loso_win_df):\n'
    '    yt = loso_win_df["true_idx"].astype(int).values\n'
    '    yp = loso_win_df["pred_idx"].astype(int).values\n'
    '    print("\\n" + "="*60)\n'
    '    print("LOSO -- WINDOW-LEVEL (all subjects pooled)")\n'
    '    print("="*60)\n'
    '    print(f"Window accuracy: {(yt==yp).mean():.4f}")\n'
    '    print(classification_report(yt, yp,\n'
    '        target_names=[IDX_TO_LABEL[i] for i in range(NUM_CLASSES)], zero_division=0))\n'
    '    print("Confusion matrix:")\n'
    '    print(confusion_matrix(yt, yp, labels=list(range(NUM_CLASSES))))\n'
    '\n'
    'if len(loso_trial_df):\n'
    '    yt = loso_trial_df["true_idx"].astype(int).values\n'
    '    yp = loso_trial_df["trial_pred_idx"].astype(int).values\n'
    '    print("\\n" + "="*60)\n'
    '    print("LOSO -- TRIAL-LEVEL (all subjects pooled)")\n'
    '    print("="*60)\n'
    '    print(f"Trial accuracy: {(yt==yp).mean():.4f}")\n'
    '    print(classification_report(yt, yp,\n'
    '        target_names=[IDX_TO_LABEL[i] for i in range(NUM_CLASSES)], zero_division=0))\n'
    '    print("Confusion matrix:")\n'
    '    print(confusion_matrix(yt, yp, labels=list(range(NUM_CLASSES))))\n'
    '    print("\\nPer-subject window accuracies:")\n'
    '    for sid, acc, n in loso_accs:\n'
    '        print(f"  {sid}: {acc:.3f}  ({n} windows)")\n'
    '    mean_loso = float(np.mean([a for _,a,_ in loso_accs]))\n'
    '    std_loso  = float(np.std( [a for _,a,_ in loso_accs]))\n'
    '    print(f"\\nMean LOSO window accuracy: {mean_loso:.4f} +/- {std_loso:.4f}")\n'
)

c = c.rstrip('\n') + '\n' + LOSO_BLOCK
assert 'LOSO CROSS-SUBJECT' in c, 'P6 FAILED'
print('P6 ok')

with open(TRAIN, 'w', encoding='utf-8') as f:
    f.write(c)
print('patch4 saved')
